"""Writers producing LOBSTER-compatible output files."""
import numpy as np
from . import __version__


def atom_label(structure, ia):
    return f"{structure.symbol_of_atom[ia]}{ia + 1}"


def _orb_name(basis, mu):
    return basis.functions[mu].name


def write_car(path, kind, structure, basis, pairs, res_per_spin, egrid, efermi, all_points=False):
    """COHPCAR/COOPCAR/COBICAR.lobster"""
    name = {"cohp": "pCOHP", "coop": "pCOOP", "cobi": "COBI"}[kind]
    nspin = len(res_per_spin)
    # interaction list: for each pair the atom interaction, then orbital pairs if orbitalwise
    labels = []
    cols = []            # list of (ip, mu_local or None, nu_local or None)
    for p in pairs:
        la, lb = atom_label(structure, p.iA), atom_label(structure, p.iB)
        labels.append(f"No.{p.index}:{la}->{lb}({p.dist:.17g})")
        cols.append((p.index - 1, None, None))
        if p.orbitalwise:
            slA, slB = basis.atom_slices[p.iA], basis.atom_slices[p.iB]
            for i, mu in enumerate(range(slA.start, slA.stop)):
                for j, nu in enumerate(range(slB.start, slB.stop)):
                    labels.append(f"No.{p.index}:{la}[{_orb_name(basis, mu)}]->{lb}[{_orb_name(basis, nu)}]({p.dist:.17g})")
                    cols.append((p.index - 1, i, j))
    nE = egrid.n
    with open(path, "w") as f:
        f.write(f"ESCALE ; {name} file generated by gpucohp {__version__} (LOBSTER-compatible). "
                f"Energy is shifted such that the Fermi level lies at 0 eV.\n")
        f.write(f"{len(labels) + 1:10d}{nspin:11d}{nE:11d}  {egrid.emin + efermi:12.5e} {egrid.E[-1] + efermi:13.5e} {efermi:13.5e} \n")
        f.write("Average\n")
        for lab in labels:
            f.write(lab + "\n")
        data = [egrid.E]
        for s in range(nspin):
            r = res_per_spin[s]
            npairs = len(pairs)
            avg = r["atom"].sum(axis=0) / npairs
            avg_i = r["atom_int"].sum(axis=0) / npairs
            data += [avg, avg_i]
            for (ip, i, j) in cols:
                if i is None:
                    data += [r["atom"][ip], r["atom_int"][ip]]
                else:
                    data += [r["orb"][ip][i, j], r["orb_int"][ip][i, j]]
        arr = np.array(data).T
        for row in (arr if all_points else arr[1:]):   # Gaussian mode: LOBSTER omits the first grid point
            f.write(" ".join(f"{v:9.5f}" for v in row) + " \n")


def write_ilist(path, kind, structure, basis, pairs, res_per_spin):
    """ICOHPLIST/ICOOPLIST/ICOBILIST.lobster"""
    tag = {"cohp": "COHP", "coop": "COOP", "cobi": "COBI"}[kind]
    nspin = len(res_per_spin)
    with open(path, "w") as f:
        f.write(f"  {tag}#    atomMU    atomNU   distance   translation   I{tag} (at) eF \n")
        f.write(" " * 58 + "for spin 1 " + ("     for spin 2 " if nspin == 2 else "") + "\n")
        for p in pairs:
            la, lb = atom_label(structure, p.iA), atom_label(structure, p.iB)
            vals = "".join(f"{res_per_spin[s]['at_ef'][p.index - 1]:15.5f} " for s in range(nspin))
            f.write(f"{p.index:7d} {la:>9s} {lb:>9s} {p.dist:10.5f} {p.cell[0]:5d} {p.cell[1]:3d} {p.cell[2]:3d} {vals}\n")
            if p.orbitalwise:
                slA, slB = basis.atom_slices[p.iA], basis.atom_slices[p.iB]
                for i, mu in enumerate(range(slA.start, slA.stop)):
                    for j, nu in enumerate(range(slB.start, slB.stop)):
                        vals = "".join(f"{res_per_spin[s]['orb_at_ef'][p.index - 1][i, j]:15.5f} " for s in range(nspin))
                        f.write(f"{p.index:7d} {la + '_' + _orb_name(basis, mu):>9s} {lb + '_' + _orb_name(basis, nu):>9s}"
                                f" {p.dist:10.5f} {p.cell[0]:5d} {p.cell[1]:3d} {p.cell[2]:3d} {vals}\n")


def write_doscar(path, structure, basis, dos_per_spin, egrid, efermi, zvals):
    nspin = len(dos_per_spin)
    st = structure
    alen = np.linalg.norm(st.lattice, axis=1)
    nE = egrid.n
    with open(path, "w") as f:
        f.write(f"{st.natoms:4d}{st.natoms:5d}    1    1\n")
        f.write(f"  {st.volume:.7e}  {alen[0]*1e-10:.7e}  {alen[1]*1e-10:.7e}  {alen[2]*1e-10:.7e}  5.0000000e-16\n")
        f.write("            1.000000e-04\n")
        f.write("  CAR\n")
        f.write(f" DOS and projected DOS file by gpucohp {__version__} (LOBSTER-compatible). "
                f"Energy is shifted such that the Fermi level lies at 0 eV. \n")
        f.write(f"{egrid.E[-1] + efermi:16.8f}{egrid.emin + efermi:17.8f}{nE:6d}{efermi:17.8f}{1.0:15.8f}\n")
        for i in range(nE):
            row = [egrid.E[i]]
            for s in range(nspin):
                row.append(dos_per_spin[s]["total"][i])
            for s in range(nspin):
                row.append(dos_per_spin[s]["total_int"][i])
            f.write(" ".join(f"{v:9.5f}" for v in row) + "\n")
        for ia in range(st.natoms):
            sl = basis.atom_slices[ia]
            names = " ".join(_orb_name(basis, mu) for mu in range(sl.start, sl.stop))
            f.write(f"{egrid.E[-1]:16.8f}{egrid.emin:17.8f}{nE:6d}{efermi:17.8f}{1.0:15.8f}; Z= {int(zvals[ia])}; {names} \n")
            for i in range(nE):
                row = [egrid.E[i]]
                for mu in range(sl.start, sl.stop):
                    for s in range(nspin):
                        row.append(dos_per_spin[s]["pdos"][mu, i])
                f.write(" ".join(f"{v:9.5f}" for v in row) + "\n")


def write_charge(path, structure, mull_atoms, loew_atoms, zval_atoms):
    with open(path, "w") as f:
        f.write("MULLIKEN and LOEWDIN POPULATION ANALYSIS \n\n")
        f.write("  atom#    atom      Mulliken charge       Loewdin charge\n")
        qm = zval_atoms - mull_atoms
        ql = zval_atoms - loew_atoms
        for ia in range(structure.natoms):
            f.write(f"{ia + 1:7d}{structure.symbol_of_atom[ia]:>8s}{qm[ia]:21.2f}{ql[ia]:22.2f} \n")
        f.write(f"\n          total{qm.sum():21.2f}{ql.sum():22.2f} \n")


def write_grosspop(path, structure, basis, mull, loew):
    """GROSSPOP.lobster; mull/loew are lists with one (nb,) array per spin."""
    ns = len(mull)
    cols = [(m, f"For spin {s + 1}") for s, m in enumerate(mull)] + [(l, f"For spin {s + 1}") for s, l in enumerate(loew)]
    with open(path, "w") as f:
        f.write("Mulliken and Loewdin gross orbital population \n\n")
        f.write("  atom#    atom   basisfunction" + "    Mulliken GP" * ns + "     Loewdin GP" * ns + "\n")
        f.write(" " * 30 + "".join(f"{lab:>15s}" for _, lab in cols) + "\n")
        for ia in range(structure.natoms):
            sl = basis.atom_slices[ia]
            first = True
            for mu in range(sl.start, sl.stop):
                head = f"{ia + 1:7d}{structure.symbol_of_atom[ia]:>8s}" if first else " " * 15
                first = False
                f.write(f"{head}{_orb_name(basis, mu):>15s}" + "".join(f"{v[mu]:15.2f}" for v, _ in cols) + "\n")
            f.write(f"{'':15s}{'total':>15s}" + "".join(f"{v[sl].sum():15.2f}" for v, _ in cols) + "\n\n\n")


def write_bandoverlaps(path, engine, threshold=1e-5):
    wav = engine.wav
    n = 0
    with open(path, "w") as f:
        for s in range(wav.nspin):
            for ik in range(wav.nkpts):
                r = engine.results[s][ik]
                if r["band_dev"] <= threshold:
                    continue
                n += 1
                O = np.abs(r["Oorth"])
                f.write(f"Overlap Matrix (abs) of the orthonormalized projected bands for spin {s + 1}\n")
                f.write(" at k-point " + " ".join(f"{x:g}" for x in wav.kpoints[ik]) + "\n")
                f.write(f"maxDeviation is: {r['band_dev']:g}\n")
                for row in O:
                    f.write(" ".join(f"{v:11.6g}" for v in row) + "\n")
    return n
